examples:

  rails:
  - selectable_card_default: Default
  - selectable_card_single_select: Single Select
  - selectable_card_block: Block
  - selectable_card_options: With Options
  - selectable_card_image: Image Example
  - selectable_card_input: Input Variant
  - selectable_card_error: With Errors


  react:
  - selectable_card_default: Default
  - selectable_card_single_select: Single Select
  - selectable_card_block: Block
  - selectable_card_image: Image Example
  - selectable_card_input: Input Variant
  - selectable_card_error: With Errors
