examples:

  rails:
  - timeline_default: Default
  - timeline_vertical: Vertical
  - timeline_with_date: With Date
  - timeline_with_children: With Children
  - timeline_show_current_year: Show Current Year
  - timeline_with_gap: With Gap


  react:
  - timeline_default: Default
  - timeline_vertical: Vertical
  - timeline_with_date: With Date
  - timeline_with_children: With Children
  - timeline_show_current_year: Show Current Year
  - timeline_with_gap: With Gap
