examples:

  rails:
  - dialog_default: Simple
  - dialog_sizes: Sizes

  react:
  - dialog_default: Simple
  - dialog_compound_components: Complex
  - dialog_sizes: Sizes
  - dialog_scrollable: Scrollable
  - dialog_should_close_on_overlay: Overlay Click
  - dialog_status: Status Alert
  - dialog_stacked_alert: Stacked Button Alert
  - dialog_full_height: Full Height
  - dialog_full_height_placement: Full Height Placement
