examples:

  rails:
  - dialog_default: Simple
  - dialog_compound_components: Complex
  - dialog_sizes: Sizes
  - dialog_scrollable: Scrollable
  - dialog_should_close_on_overlay: Overlay Click
  - dialog_status: Status Alert
  - dialog_stacked_alert: Stacked Button Alert
  - dialog_full_height: Full Height
  - dialog_full_height_placement: Full Height Placement
  - dialog_loading: Loading
  - dialog_turbo_frames: Within Turbo Frames


  react:
  - dialog_default: Simple
  - dialog_compound_components: Complex
  - dialog_sizes: Sizes
  - dialog_scrollable: Scrollable
  - dialog_should_close_on_overlay: Overlay Click
  - dialog_status: Status Alert
  - dialog_stacked_alert: Stacked Button Alert
  - dialog_full_height: Full Height
  - dialog_full_height_placement: Full Height Placement
  - dialog_loading: Loading
  - dialog_overflow_visible: Overflow Visible

  swift:
  - dialog_default_swift: Simple
  - dialog_sizes_swift: Sizes
  - dialog_status_swift: Status
  - dialog_props_swift: ""
  
