examples:
  
  rails:
  - selectable_card_icon_default: Default
  - selectable_card_icon_single_select: Single Select
  - selectable_card_icon_dark: Dark
  
  
  react:
  - selectable_card_icon_default: Default
  - selectable_card_icon_single_select: Single Select
  - selectable_card_icon_dark: Dark

  
