examples:

  rails:
  - textarea_default: Default
  - textarea_custom: Custom Textarea Input
  - textarea_resize: Resize
  - textarea_error: Textarea w/ Error
  - textarea_character_counter: Character Counter
  - textarea_inline: Inline
  - textarea_emoji_mask: Emoji Mask
  - textarea_required_indicator: Required Indicator
  - textarea_input_options: Input Options

  react:
  - textarea_default: Default
  - textarea_custom: Custom Textarea Input
  - textarea_resize: Resize
  - textarea_error: Textarea w/ Error
  - textarea_character_counter: Character Counter
  - textarea_inline: Inline
  - textarea_emoji_mask: Emoji Mask
  - textarea_required_indicator: Required Indicator
  - textarea_input_options: Input Options

  swift:
  - textarea_default_swift: Default
  - textarea_error_swift: Textarea w/ Error
  - textarea_props_swift: ""
