examples:
  rails:
  - card_light: Default
  - card_dark: Dark Cards
  - card_highlight: Highlight Cards
  - card_header: Header Cards
  - card_selected: Selected
  - card_padding: Padding Size
  - card_shadow: Shadow Size
  - card_content: Content Size
  - card_separator: Separator Card
  - card_border_none: No Border
  - card_radio: Radio Cards
  react:
  - card_light: Default
  - card_dark: Dark Cards
  - card_highlight: Highlight Cards
  - card_header: Header Cards
  - card_selected: Selected
  - card_padding: Padding Size
  - card_shadow: Shadow Size
  - card_content: Content Size
  - card_separator: Separator Card
  - card_border_none: No Border
  - card_radio: Radio Cards
