examples:

  react:
  - phone_number_input_default: Default
  - phone_number_input_preferred_countries: Preferred Countries
  - phone_number_input_initial_country: Initial Country
  - phone_number_input_only_countries: Only Countries
  - phone_number_input_exclude_countries: Exclude Countries
  - phone_number_input_validation: Form Validation
  - phone_number_input_clear_field: Clearing the Input Field
  - phone_number_input_access_input_element: Accessing the Input Element
  - phone_number_input_format: Format as You Type
  - phone_number_input_strict_mode: Strict Mode
  - phone_number_input_country_search: Country Search
  - phone_number_input_required_indicator: Required Indicator

  rails:
  - phone_number_input_default: Default
  - phone_number_input_preferred_countries: Preferred Countries
  - phone_number_input_initial_country: Initial Country
  - phone_number_input_only_countries: Only Countries
  - phone_number_input_exclude_countries: Exclude Countries
  - phone_number_input_validation: Form Validation
  - phone_number_input_format: Format as You Type
  - phone_number_input_strict_mode: Strict Mode
  - phone_number_input_hidden_inputs: Hidden Inputs
  - phone_number_input_country_search: Country Search
  - phone_number_input_required_indicator: Required Indicator
