examples:
  rails:
    - typeahead_default: Default
    - typeahead_custom_options: With Grouped Options
    - typeahead_default_options: With Default Options
    - typeahead_with_context: With Context
    - typeahead_with_pills: With Pills
    - typeahead_input_display: Input Display
    - typeahead_without_pills: Without Pills (Single Select)
    - typeahead_with_pills_async: With Pills (Async Data)
    - typeahead_with_pills_async_users: With Pills (Async Data w/ Users)
    - typeahead_inline: Inline
    - typeahead_multi_kit: Multi Kit Options
    - typeahead_error_state: Error State
    - typeahead_margin_bottom: Margin Bottom
    - typeahead_with_pills_color: With Pills (Custom Color)
    - typeahead_truncated_text: Truncated Text
    - typeahead_dynamic_options: Dynamic Options
    - typeahead_dynamic_options_pure_rails: Dynamic Options (Pure Rails)
    - typeahead_disabled: Disabled
    - typeahead_preserve_input: Preserve Search Input

  react:
    - typeahead_default: Default
    - typeahead_custom_options: With Grouped Options
    - typeahead_default_value: With Default Value
    - typeahead_react_hook: React Hook
    - typeahead_with_highlight: With Highlight
    - typeahead_with_pills: With Pills
    - typeahead_input_display: Input Display
    - typeahead_with_pills_async: With Pills (Async Data)
    - typeahead_with_pills_async_users: With Pills (Async Data w/ Users)
    - typeahead_with_pills_async_custom_options: With Pills (Async Data w/ Custom Options)
    - typeahead_inline: Inline
    - typeahead_multi_kit: Multi Kit Options
    - typeahead_createable: Createable
    - typeahead_async_createable: Createable (+ Async Data)
    - typeahead_error_state: Error State
    - typeahead_custom_menu_list: Custom MenuList
    - typeahead_margin_bottom: Margin Bottom
    - typeahead_with_pills_color: With Pills (Custom Color)
    - typeahead_truncated_text: Truncated Text
    - typeahead_disabled: Disabled
    - typeahead_preserve_input: Preserve Search Input
    - typeahead_required_indicator: Required Indicator
