appConfig:
    secretKeyBase: ENC[AES256_GCM,data:de3NakNnqnRRg4RdqxDCQF4WYWuXGl0qY+86Dln3bFhruhTYqSGmQsv+7Rw7vajQqM9qwoC9+1kbJV0JxONwFRSSLqLduv0DxduXniyrL1AtpnuLQzsO5EcJDlb11dqqvfIRmNcJK1724nW4AKW/kRSspfqjllR2GKRxmRCJKRE=,iv:lXmw3b9V+9+utfvEieJAhZSv+GlzxF0Km+CI5+GjWVA=,tag:f+A+9xx19DccNSjFPruhtg==,type:str]
font_awesome_auth_token: ENC[AES256_GCM,data:yPhQovCkm/Hyfdj4h+1Ka1E2WE2qNzURhuugXXYvmcCIaQ3V,iv:xfYzQTZAXblgg7qm6j+XEvpq6eUU/x66yGFKp7su9hQ=,tag:CwwubzNIj3dz1NWOak0Umg==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:205083374951:key/d46e780d-ee0a-4a7d-b049-0443e1b91d41
        created_at: '2021-05-04T13:31:11Z'
        enc: AQICAHjD4+PGrfNOURZm5p39Rxa0oVLr81xX3U8gvQwj2QeLTgEXXpjb9fTfQVWH/zd8gS3+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIiT05R23xdmVD8wmAgEQgDvyv5dJRuHffjph8aYkH/NzhsgEGzVXdmztzv6Kc5PC57GzpComtF3rmzOHptUL8tdWc1r1RrBHGdH3qw==
        aws_profile: ""
    -   arn: arn:aws:kms:us-east-1:205083374951:key/d46e780d-ee0a-4a7d-b049-0443e1b91d41
        role: arn:aws:iam::205083374951:role/UX
        created_at: '2021-05-04T13:31:11Z'
        enc: AQICAHjD4+PGrfNOURZm5p39Rxa0oVLr81xX3U8gvQwj2QeLTgHbYHaWiTC8FtTQTkj5eIpPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQME5yHUCuYZveRpEKuAgEQgDs02FsUNbNp/ed2hBu4WtfGvoAizo+HSKrTnhR+7y0+lh2CAaKGxgTJJZqhifOTw44rWhcVKC4t4cuHeQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-11-16T20:36:59Z'
    mac: ENC[AES256_GCM,data:UTjI0qCNC0zCpxkZ5PUChvWlci5ozrL7DQRH0jl28Ua/QxE5WcXs0ceMy5sM2kNxIdLzDaH3zWbsXcILUiv5ZWDZnjhyAZtD4vX3iJUmjOUevX7EHcvJm81pNVOt9E6wFeT+US3GepL3o7EV7iAxwSglXTS0zT0Oy8VpX/fTjMI=,iv:kg2ySfvK+LoWpEFq4SGi1YFJ7EBxcYLbOTluU9/EGv0=,tag:RIxUhAPTRP2DnbclAyExYw==,type:str]
    pgp:
    -   created_at: '2021-05-04T13:31:11Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2NdqJ8wZEUFARAAtxS9LMQwfoT3lsr82Od8R9tB22UqF2L7PKgDBY22JdV3
            797ClnSznP9eJpExCuUyqaNkqi4DDQPs3Pul7S7IhA1k5Q8f+HKMURwuoSGpe/aF
            64FuABPQsxMuVV0Fv+LS8eIZetSCPs2r/hTFW6MN9FIT0UE1LY2eeDqMuT9EV3qq
            fuiwgsA9HeJBL+lKyPfMk1eXqAcjygjoB/G1GpNvymgQpMGvub07C708huY7p+uM
            /wkgbSp9a4cG/aRI7EpXwEE/JXtjGF5BdcayKVWmhgv78KfLGunQKRTS3LYmXiBy
            ZSzIbB4sVy9ZHbVMgI4KmInpDBbSudYRYoNchbWuQNCJdXgtzGODdty9tusyZwh/
            /TlHabbUGM2ijo9B7pLa9ZuhfehU5atklf7vIsKezZA8Kk6ywXfj68kou9ien4L6
            dak5CvQwzjdTFnjkPsRPVZmBp6t5OeLMzPNR/wN0kI1M6oNMREkUdrigf0q+QW2Z
            lAcXZ+dN6KsOWXhe+VwhFvbAd3skmzKDqbiw/ocD0p3rQWR64TA4ZsdKND+H7ItN
            IFrf6GuFY5II+ROCOpgiulTzfr5O4Eq7jroHho4FEuF8qG08HeRwRvvYv7H9wjU9
            1jaUn6EASNYUiauuS7Fy0u57m2fACrWId5459zJBBQ5AhHP4rDV0ratJY9zPrDvS
            5gFM4qhfwN5D8waGjPh3hnUPs8bhhHAR5WyGXcJQF4jY3DJaW0NmDfhFLzMklv37
            JhR7Q2pdMA4HYe6gSuj4Ko/kkToHzK+49Uvy7Vj7c0wIK+KN7YhWAA==
            =uTkc
            -----END PGP MESSAGE-----
        fp: C534CBAA229396B3FFC0CBB8FEFCDD8B6EB6B73B
    -   created_at: '2021-05-04T13:31:11Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA4Ms0+/IoZU/AQgAEaxyM8E2JblY8Ue3B1DWSYueItr2mqd0lf+r8fDxERdP
            ijxs0L898TlF0LbpAai0IskIf+1NzSelPNy9X6QJDJafR7QTsM3vq0hHq8duXa9s
            CrxfCMUx7xk2brAR177/OtktXPoLH9FEu3fasNkSJJuthOxFHVnOP1/XSLNobDhG
            i8gqinGIUH6eV7GKhmHbTI8ZwV2Rw4ZFeuMOeYufdM6x1N4GYYA7Z9V1Ng8QLdqi
            aZD8YRCTTz7duX3Owtjd00BmUEv1WcoM/2cC5cuLHUu2s79IRoAkZ6NfFZHX8pVr
            vbtY9dRhILTFJIm9nBpbcdoAUiDO5iKUkuwpF6684dLmAcIS8MTd7aAANi7p45Co
            c/E67fY5ZBiaXAKieIjomWuAGjGLOzcktxj9jj/ors8aYEv497Mw6rT8yBZoeo/z
            ieRRxRGzRnGqP+771+5mM10z4kcVsvoA
            =EZem
            -----END PGP MESSAGE-----
        fp: 181D7230C1982F01D9751710F0C07D7B2AC4F268
    unencrypted_suffix: _unencrypted
    version: 3.5.0
