examples:

  rails:
  - date_default: Default
  - date_variants: Variants
  - date_alignment: Alignment
  - date_timezone: Timezones
  - date_with_show_current_year: Show Current Year
  - date_unstyled: Unstyled

  react:
  - date_default: Default
  - date_variants: Variants
  - date_alignment: Alignment
  - date_with_show_current_year: Show Current Year
  - date_unstyled: Unstyled

  swift:
  - date_default_swift: Default
  - date_variants_swift: Variants
  - date_alignment_swift: Alignment
  - date_unstyled_swift: Unstyled
  - date_props_swift: ""
