examples:
  rails:
    - date_default: Default
    - date_variants: Variants
    - date_alignment: Alignment
    - date_timezone: Timezones
    - date_unstyled: Unstyled

  react:
    - date_default: Default
    - date_variants: Variants
    - date_alignment: Alignment
    - date_unstyled: Unstyled
