examples:
  rails:
  - body_light: Default
  - body_block: Block
  - body_articles: Best settings for articles
  - body_styled: Styled tags
  - body_truncate: Truncate
  - body_with_phone_number: Phone Number

  react:
  - body_light: Default
  - body_block: Block
  - body_articles: Best settings for articles
  - body_styled: Styled tags
  - body_truncate: Truncate
  - body_with_phone_number: Phone Number
