examples:

  rails:
  - toggle_default: Default State
  - toggle_disabled: Disabled
  - toggle_name: Name and Value
  - toggle_custom: Custom checkbox input
  - toggle_custom_radio: Custom radio inputs
  - toggle_options: Toggle w/ Options

  react:
  - toggle_default: Default State
  - toggle_disabled: Disabled
  - toggle_name: Name and Value
  - toggle_custom: Custom checkbox input
  - toggle_custom_radio: Custom radio inputs

  swift:
    - toggle_default_swift: Default State
    - toggle_name_swift: Name and Value
    - toggle_props_swift: ""
