examples:

  rails:
  - line_graph_default: Default
  - line_graph_legend: Legend
  - line_graph_legend_position: Legend Position
  - line_graph_legend_nonclickable: Legend Nonclickable
  - line_graph_height: Height
  - line_graph_colors: Color Overrides


  react:
  - line_graph_default: Default
  - line_graph_pb_styles: Playbook Styles
  - line_graph_legend: Legend
  - line_graph_legend_position: Legend Position
  - line_graph_legend_nonclickable: Legend Nonclickable
  - line_graph_height: Height
  - line_graph_colors: Color Overrides
