examples:
  rails:
  - dropdown_default: Default
  - dropdown_subcomponent_structure_rails: Subcomponent Structure
  - dropdown_with_label: With Label
  - dropdown_with_custom_options_rails: Custom Options
  - dropdown_with_custom_display_rails: Custom Display
  - dropdown_with_custom_trigger_rails: Custom Trigger
  - dropdown_with_custom_padding: Custom Option Padding
  - dropdown_error: Dropdown with Error
  - dropdown_default_value: Default Value
  - dropdown_blank_selection: Blank Selection
  - dropdown_subtle_variant: Subtle Variant

  react:
  - dropdown_default: Default
  - dropdown_subcomponent_structure: Subcomponent Structure
  - dropdown_with_label: With Label
  - dropdown_with_custom_options: Custom Options
  - dropdown_with_custom_display: Custom Display
  - dropdown_with_custom_trigger: Custom Trigger
  - dropdown_with_custom_padding: Custom Option Padding
  - dropdown_error: Dropdown with Error
  - dropdown_default_value: Default Value
  - dropdown_blank_selection: Blank Selection
  - dropdown_subtle_variant: Subtle Variant
  # - dropdown_with_autocomplete: Autocomplete
  # - dropdown_with_autocomplete_and_custom_display: Autocomplete with Custom Display
  # - dropdown_with_external_control: useDropdown Hook
  # - dropdown_with_hook: useDropdown Hook with Any Trigger

