examples:

  rails:
  - flex_default: Default
  - flex_inline: Inline
  - flex_reverse: Reverse
  - flex_wrap: Wrap
  - flex_spacing: Spacing
  - flex_justify: Justify
  - flex_align: Align
  - flex_gap: Gap
  - flex_item: Flex Item
  - flex_align_self: Flex Item - Align Self




  react:
  - flex_default: Default
  - flex_inline: Inline
  - flex_reverse: Reverse
  - flex_wrap: Wrap
  - flex_spacing: Spacing
  - flex_justify: Justify
  - flex_align: Align
  - flex_gap: Gap
  - flex_item_example: Flex Item
  - flex_align_self: Flex Item - Align Self
