examples:

  rails:
  - tooltip_default: Default
  - tooltip_selectors: Using Common Selectors
  - tooltip_with_icon_circle: Icon Circle Tooltip
  - tooltip_show_tooltip: Show Tooltip

  react:
  - tooltip_sizing: Tooltip Sizing
  - tooltip_default_react: Default
  - tooltip_interaction: Content Interaction
  - tooltip_margin: Margin
  - tooltip_icon: Tooltip with Icon
  - tooltip_delay: Delay
  - tooltip_show_tooltip_react: Show Tooltip
