examples:

  rails:
  - tooltip_default: Default
  - tooltip_selectors: Using Common Selectors
  - tooltip_white: White
  - tooltip_with_icon_circle: Icon Circle Tooptip

  react:
  - tooltip_default_react: Default
  - tooltip_interaction: Content Interaction
  - tooltip_margin: Margin
  - tooltip_icon: Tooltip with Icon
