examples:

  rails:
  - section_separator_line: Line Separator
  - section_separator_dashed: Dashed Separator
  - section_separator_text: Text Separator
  - section_separator_vertical: Vertical
  - section_separator_children: Children
  - section_separator_color: Color

  react:
  - section_separator_line: Line Separator
  - section_separator_dashed: Dashed Separator
  - section_separator_text: Text Separator
  - section_separator_vertical: Vertical
  - section_separator_children: Children
  - section_separator_color: Color


  swift:
  - section_separator_line_swift: Line Separator
  - section_separator_dashed_swift: Dashed Separator
  - section_separator_text_swift: Text Separator
  - section_separator_vertical_swift: Vertical
  - section_separator_children_swift: Children
  - section_separator_props_swift: ""
