examples:
  
  rails:
  - fixed_confirmation_toast_default: Default
  - fixed_confirmation_toast_multi_line: Multi Line
  - fixed_confirmation_toast_close: Click to Close
  - fixed_confirmation_toast_positions: Click to Show Positions
  - fixed_confirmation_toast_auto_close: Click to Show Auto Close
  
  react:
  - fixed_confirmation_toast_default: Default
  - fixed_confirmation_toast_multi_line: Multi Line
  - fixed_confirmation_toast_close: Click to Close
  - fixed_confirmation_toast_positions: Click to Show Positions
  - fixed_confirmation_toast_auto_close: Click to Show Auto Close
