examples:
  rails:
  - button_default: Button Variants
  - button_default_dark: Button Variants Dark
  - button_full_width: Button Full Width
  - button_link: Button Links
  - button_loading: Button Loading
  - button_block_content: Button Block Content
  - button_accessibility: Button Accessibility Options
  - button_options: Button Additional Options
  react:
  - button_default: Button Variants
  - button_default_dark: Button Variants Dark
  - button_full_width: Button Full Width
  - button_link: Button Links
  - button_loading: Button Loading
  - button_block_content: Button Block Content
  - button_accessibility: Button Accessibility Options
  - button_options: Button Additional Options
