examples:

  rails:
  - form_form_with: Default
  - form_form_with_validate: Default + Validation
  - form_form_with_loading: Default + Loading
  - form_form_with_required_indicator: Required Indicator
