examples:

  rails:
  - background_light: Default
  - background_white: White
  - background_gradient: Gradient
  - background_image: Image
  - background_status: Status
  - background_status_subtle: Status Subtle
  - background_category: Category
  - background_size: Size

  react:
  - background_light: Default
  - background_white: White
  - background_gradient: Gradient
  - background_image: Image
  - background_status: Status
  - background_status_subtle: Status Subtle
  - background_category: Category
  - background_size: Size
  - background_overlay: Overlay
