examples:

  rails:
  - background_light: Light
  - background_white: White
  - background_gradient: Gradient
  - background_image: Image
  - background_status: Status
  - background_category: Category
  - background_transition: Transition

  react:
  - background_light: Light
  - background_white: White
  - background_gradient: Gradient
  - background_image: Image
  - background_status: Status
  - background_category: Category
  - background_transition: Transition
