examples:
  rails:
    - text_input_default: Default
    - text_input_error: With Error
    - text_input_custom: Custom
    - text_input_disabled: Disabled
    - text_input_add_on: Add On
    - text_input_inline: Inline
    - text_input_no_label: No Label
    - text_input_options: Input Options
  react:
    - text_input_default: Default
    - text_input_error: With Error
    - text_input_custom: Custom
    - text_input_disabled: Disabled
    - text_input_add_on: Add On
    - text_input_inline: Inline
    - text_input_no_label: No Label
