examples:
  rails:
  - text_input_default: Default
  - text_input_error: With Error
  - text_input_custom: Custom
  - text_input_disabled: Disabled
  - text_input_add_on: Add On
  - text_input_inline: Inline
  - text_input_no_label: No Label
  - text_input_options: Input Options
  - text_input_mask: Mask
  - text_input_autocomplete: Autocomplete
  
  react:
  - text_input_default: Default
  - text_input_error: With Error
  - text_input_custom: Custom
  - text_input_disabled: Disabled
  - text_input_add_on: Add On
  - text_input_inline: Inline
  - text_input_no_label: No Label
  - text_input_mask: Mask
  - text_input_sanitize: Sanitized Masked Input
  - text_input_autocomplete: Autocomplete


  swift:
    - text_input_default_swift: Default
    - text_input_error_swift: With Error
    - text_input_disabled_swift: Disabled
    - text_input_add_on_swift: Add On
    - text_input_props_swift: ""
