examples:

  rails:
  - date_time_stacked_default: Default
  - date_time_stacked_show_current_year: Show Current Year

  react:
  - date_time_stacked_default: Default
  - date_time_stacked_show_current_year: Show Current Year
  
  swift:
  - date_time_stacked_default_swift: Default
  - date_time_stacked_props_swift: ""

