examples:

  rails:
  - treemap_chart_default: Default

  react:
  - treemap_chart_default: Default
  - treemap_chart_grouped_data: Grouped Data
  - treemap_chart_drillable: Drillable
  - treemap_chart_colors: Color Overrides
  - treemap_chart_tooltip: Tooltip Customization
