examples:

  rails:
  - date_stacked_default: Default
  - date_stacked_not_current_year: Not Current Year
  - date_stacked_current_year: Show Current Year
  - date_stacked_reverse: Day & Month Reverse
  - date_stacked_sizes: Sizes
  - date_stacked_align: Alignment
  - date_stacked_bold: Bold


  react:
  - date_stacked_default: Default
  - date_stacked_not_current_year: Not Current Year
  - date_stacked_current_year: Show Current Year
  - date_stacked_reverse: Day & Month Reverse
  - date_stacked_sizes: Sizes
  - date_stacked_bold: Bold

  swift:
  - date_stacked_default_swift: Default
  - date_stacked_not_current_year_swift: Not Current Year
  - date_stacked_reversed_swift: Day & Month Reverse
  - date_stacked_bold_swift: Bold
  - date_stacked_props_swift: ""
