examples:

  rails:
  - multiple_users_default: Default
  - multiple_users_reverse: Reverse
  - multiple_users_size: Size
  - multiple_users_with_tooltip: With Tooltip


  react:
  - multiple_users_default: Default
  - multiple_users_reverse: Reverse
  - multiple_users_size: Size
  - multiple_users_with_tooltip: With Tooltip

  swift:
  - multiple_users_default_swift: Default
  - multiple_users_reverse_swift: Reverse
  - multiple_users_size_swift: Small
  - multiple_users_props_swift: ""