---
full_page_samples:
- analytics_dashboard
- conference_statistics
- crm_client_list
- news_magazine
- trending_repositories
- crowdsourced_posts
- music_app
card_samples:
- card_dashboard
prop_samples:
- global_positioning
