examples:

  rails:
  - bar_graph_default: Default
  - bar_graph_legend: Legend
  - bar_graph_legend_position: Legend Position
  - bar_graph_height: Height
  - bar_graph_spline: Spline
  - bar_graph_colors: Color Overrides
  - bar_graph_custom_rails: Custom Overrides
  - bar_graph_stacked: Stacked
  - bar_graph_negative_numbers: Negative Numbers
  - bar_graph_secondary_y_axis: Secondary Y-Axis
  - bar_graph_horizontal: Custom Options From Highcharts


  react:
  - bar_graph_default: Default
  - bar_graph_legend: Legend
  - bar_graph_legend_position: Legend Position
  - bar_graph_legend_non_clickable: Legend Non Clickable
  - bar_graph_height: Height
  - bar_graph_spline: Spline
  - bar_graph_colors: Color Overrides
  - bar_graph_stacked: Stacked
  - bar_graph_negative_numbers: Negative Numbers
  - bar_graph_secondary_y_axis: Secondary Y-Axis
  - bar_graph_horizontal: Horizontal Bar Graph
