examples:
  rails:
  - multi_level_select_default: Default
  - multi_level_select_single: Single Select
  - multi_level_select_single_children_only: Single Select w/ Hidden Radios
  - multi_level_select_return_all_selected: Return All Selected
  - multi_level_select_selected_ids: Selected Ids
  - multi_level_select_with_form: With Form
  - multi_level_select_color: With Pills (Custom Color)
  - multi_level_select_reset: Reset Selection
  - multi_level_select_label: With Label
  - multi_level_select_error: Error
  - multi_level_select_disabled: Disabled Input
  - multi_level_select_disabled_options_default: Disabled Options (Default)
  - multi_level_select_disabled_options: Disabled Options (Return All Selected)
  - multi_level_select_disabled_options_parent_default: Disabled Parent Option (Default)
  - multi_level_select_disabled_options_parent: Disabled Parent Option (Return All Selected)
  - multi_level_select_single_disabled: Disabled Options (Single Select)

  react:
  - multi_level_select_default: Default
  - multi_level_select_react_hook: React Hook
  - multi_level_select_single: Single Select
  - multi_level_select_single_children_only: Single Select w/ Hidden Radios
  - multi_level_select_return_all_selected: Return All Selected
  - multi_level_select_selected_ids_react: Selected Ids
  - multi_level_select_color: With Pills (Custom Color)
  - multi_level_select_with_children: Checkboxes With Children
  - multi_level_select_with_children_with_radios: Single Select With Children
  - multi_level_select_label: With Label
  - multi_level_select_error: Error
  - multi_level_select_disabled: Disabled Input
  - multi_level_select_disabled_options_default: Disabled Options (Default)
  - multi_level_select_disabled_options: Disabled Options (Return All Selected)
  - multi_level_select_disabled_options_parent_default: Disabled Parent Option (Default)
  - multi_level_select_disabled_options_parent: Disabled Parent Option (Return All Selected)
  - multi_level_select_single_disabled: Disabled Options (Single Select)
