examples:
  rails:
  - advanced_table_default: Default (Required Props)
  react:
  - advanced_table_default: Default (Required Props)
  - advanced_table_loading: Loading State
  - advanced_table_sort: enable Sorting
  - advanced_table_sort_control: Sort Control
  - advanced_table_expanded_control: Expanded Control
  - advanced_table_subrow_headers: SubRow Headers
  - advanced_table_collapsible_trail: Collapsible Trail
  - advanced_table_table_options: Table Options
  - advanced_table_table_props: Table Props
  - advanced_table_inline_row_loading: inline Row Loading

