examples:
  rails:
    - popover_default: Default
    - popover_list: With any children
    - popover_click_outside: Close on click outside
    - popover_click_inside: Close on click inside
    - popover_click_any: Close on click anywhere

  react:
    - popover_default: Default
    - popover_list: With any children
    - popover_portal: Use with `portal` option
    - popover_click_outside: Close on click outside
    - popover_click_inside: Close on click inside
    - popover_click_any: Close on click anywhere