examples:
  rails:
    - popover_default: Default
    - popover_list: Example as dropdown
    - popover_close: Close Options
    - popover_z_index: Set Z-Index
    - popover_scroll_height: Scroll and Height Settings
    - popover_actionable_content: With Actionable Content
    - popover_append_to: Append To

  react:
    - popover_default: Default
    - popover_list: Dropdown example
    - popover_close: Close Options
    - popover_z_index: Set Z-Index
    - popover_scroll_height: Scroll and Height Settings
    - popover_actionable_content: With Actionable Content
    - popover_append_to: Append To
