examples:
  rails:
    - avatar_default: Default
    - avatar_monogram: Monogram
    - avatar_no_image: "Bad Image Link"
    - avatar_status: Status
    - avatar_circle_icon_component_overlay: Icon Circle Component Overlay
    - avatar_badge_component_overlay: Badge Component Overlay
    - avatar_grayscale: Grayscale
  react:
    - avatar_default: Default
    - avatar_monogram: Monogram
    - avatar_no_image: "Bad Image Link"
    - avatar_status: Status
    - avatar_circle_icon_component_overlay: Icon Circle Component Overlay
    - avatar_badge_component_overlay: Badge Component Overlay
    - avatar_grayscale: Grayscale
  swift:
    - avatar_default_swift: Default
    - avatar_monogram_swift: Monogram
    - avatar_props_swift: ""