examples:
  rails:
    - avatar_default: Default
    - avatar_monogram: Monogram
    - avatar_no_image: "Bad Image Link"
    - avatar_status: Status
  react:
    - avatar_default: Default
    - avatar_monogram: Monogram
    - avatar_no_image: "Bad Image Link"
    - avatar_status: Status
