examples:
  rails:
    - table_sm: Small
    - table_md: Medium
    - table_lg: Large
    - table_side_highlight: Side Highlight
    - table_container: Table Container Off
    - table_disable_hover: Disable Hover
    - table_multiline: Multi-line
    - table_single_line: Force Single Line
    - table_data_table: Data Table
    - table_responsive_table: Responsive Tables
 
  react:
    - table_sm: Small
    - table_md: Medium
    - table_lg: Large
    - table_side_highlight: Side Highlight
    - table_container: Table Container Off
    - table_disable_hover: Disable Hover
    - table_multiline: Multi-line
    - table_single_line: Force Single Line
    - table_data_table: Data Table
    - table_responsive_table: Responsive Tables
