examples:

  rails:
  # - collapsible_default: Default
  # - collapsible_size: Size
  # - collapsible_color: Color
  # - collapsible_icons: Custom Icons

  react:
  # - collapsible_default: Default
  # - collapsible_size: Size
  # - collapsible_color: Color
  - collapsible_icons: Custom Icons