examples:

  rails:
  - collapsible_default: Default
  - collapsible_size: Icon Size
  - collapsible_color: Icon Color
  - collapsible_icons: Custom Icons
  - collapsible_external_controls: Toggle Collapsible With External Controls
  - collapsible_external_controls_multiple: Toggle All Collapsibles With One Control

  react:
  - collapsible_default: Default
  - collapsible_size: Icon Size
  - collapsible_color: Icon Color
  - collapsible_icons: Custom Icons
  - collapsible_state: useCollapsible Hook

  swift:
  - collapsible_default_swift: Default
  - collapsible_sizes_swift: Sizes
  - collapsible_colors_swift: Colors
