examples:

  rails:
  - collapsible_default: Default
  - collapsible_size: Icon Size
  - collapsible_color: Icon Color
  - collapsible_icons: Custom Icons
  - collapsible_external_controls: Toggle Collapsible With External Controls
  - collapsible_external_controls_multiple: Toggle All Collapsibles With One Control
  - collapsible_custom_main_rails: Custom Main Section

  react:
  - collapsible_default: Default
  - collapsible_size: Icon Size
  - collapsible_color: Icon Color
  - collapsible_icons: Custom Icons
  - collapsible_state: useCollapsible Hook
  - collapsible_custom_main: Custom Main Section


  swift:
  - collapsible_default_swift: Default
  - collapsible_sizes_swift: Sizes
  - collapsible_colors_swift: Colors
  - collapsible_props_table: ""
