examples:
  
  rails:
  - pill_default: Default
  - pill_variants: Variants
  - pill_example: Example
 
  
  
  react:
  - pill_default: Default
  - pill_variants: Variants
  - pill_example: Example

  swift:
  - pill_default_swift: Default
  - pill_variants_swift: Variants
  - pill_props_swift: ""
  