examples:
  rails:
  - icon_default: Icon Default
  - icon_rotate: Icon Rotate
  - icon_flip: Icon Flip
  - icon_animate: Icon Animation
  - icon_pull: Icon Pull
  - icon_border: Icon Border
  - icon_sizes: Icon Sizes
  - icon_custom: Icon Custom
  - icon_fa_kit: Icon with FontAwesome Kit
  - icon_color: Icon Color

  react:
  - icon_default: Icon Default
  - icon_rotate: Icon Rotate
  - icon_flip: Icon Flip
  - icon_animate: Icon Animation
  - icon_pull: Icon Pull
  - icon_border: Icon Border
  - icon_sizes: Icon Sizes
  - icon_custom: Icon Custom
  - icon_fa_kit: Icon with FontAwesome Kit
  - icon_color: Icon Color

  swift:
  - icon_default_swift: Icon Default
  - icon_rotate_swift: Icon Rotate
  - icon_flip_swift: Icon Flip
  - icon_border_swift: Icon Border
  - icon_sizes_swift: Icon Sizes
  - icon_props_swift: Props
