examples:
  rails:
  - icon_default: Icon Default
  - icon_rotate: Icon Rotate
  - icon_flip: Icon Flip
  - icon_animate: Icon Animation
  - icon_pull: Icon Pull
  - icon_border: Icon Border
  - icon_sizes: Icon Sizes
  - icon_custom: Icon Custom
  - icon_fa_kit: Icon with FontAwesome Kit
  - icon_svg: Icon SVG

  react:
  - icon_default: Icon Default
  - icon_rotate: Icon Rotate
  - icon_flip: Icon Flip
  - icon_animate: Icon Animation
  - icon_pull: Icon Pull
  - icon_border: Icon Border
  - icon_sizes: Icon Sizes
  - icon_custom: Icon Custom
  - icon_fa_kit: Icon with FontAwesome Kit
