examples:

  rails:
  - currency_variants: Variants
  - currency_size: Size
  - currency_alignment: Alignment
  - currency_no_symbol: No Symbol
  - currency_abbreviated: Abbreviate Larger Amounts
  - currency_matching_decimals: Matching Decimals
  - currency_unstyled: Unstyled

  react:
  - currency_variants: Variants
  - currency_size: Size
  - currency_alignment: Alignment
  - currency_no_symbol: No Symbol
  - currency_abbreviated: Abbreviate Larger Amounts
  - currency_matching_decimals: Matching Decimals
  - currency_unstyled: Unstyled

  swift:
  - currency_size_swift: Size
  - currency_alignment_swift: Alignment
  - currency_props_swift: ""
