examples:

  rails:
  - contact_default: Default
  - contact_with_detail: Detail Indicator
  - contact_unstyled: Unstyled


  react:
  - contact_default: Default
  - contact_with_detail: Detail Indicator
  - contact_unstyled: Unstyled


  swift:
  - contact_default_swift: Default
  - contact_with_detail_swift: Detail Indicator
  - contact_props_swift: ""