examples:

  rails:
  - form_group_default: Default
  - form_group_button: Button
  - form_group_full_width: Full Width
  - form_group_date_picker: Date Picker
  # - form_group_typeahead: Typeahead
  - form_group_select: Select
  - form_group_selectable_card: Selectable Card
  - form_group_selectable_card_icon: Selectable Card Icon


  react:
  - _test: Test
  # - form_group_default: Default
  # - form_group_button: Button
  # - form_group_full_width: Full Width
  # - form_group_date_picker: Date Picker
  # # - form_group_typeahead: Typeahead
  # - form_group_select: Select
  # - form_group_selectable_card: Selectable Card
  # - form_group_selectable_card_icon: Selectable Card Icon
