examples:

  rails:
  - date_picker_default: Default
  - date_picker_hide_icon: Hide Input Icon
  - date_picker_default_date: Default Date
  - date_picker_allow_input: Allow Input
  - date_picker_input: Input Field
  - date_picker_label: Label
  - date_picker_on_change: onChange
  - date_picker_on_close: onClose
  # - date_picker_range: Range
  - date_picker_quick_pick_rails: Range (Quick Pick)
  - date_picker_quick_pick_range_limit: Range (Quick Pick w/ “This” Range limit)
  - date_picker_quick_pick_custom: Custom Quick Pick Dates
  - date_picker_quick_pick_custom_override: Custom Quick Pick Dates (append to defaults)
  - date_picker_quick_pick_default_date: Range (Quick Pick w/ Default Date)
  - date_picker_range_pattern_rails: Range with 2 Date Pickers and a Quick Pick
  - date_picker_format: Format
  - date_picker_disabled: Disabled Dates
  - date_picker_min_max: Min Max
  - date_picker_error: Error
  - date_picker_flatpickr_methods: Flatpickr Methods
  - date_picker_hooks: Hooks
  - date_picker_year_range: Year Range
  - date_picker_anti_patterns: Anti-Patterns
  - date_picker_margin_bottom: Margin Bottom
  - date_picker_inline: Inline
  - date_picker_month_and_year: Month & Year Only
  - date_picker_week: Week
  - date_picker_time: Time Selection
  - date_picker_positions: Custom Positions
  - date_picker_positions_element: Custom Position (based on element)
  - date_picker_turbo_frames: Within Turbo Frames

  react:
  - date_picker_default: Default
  - date_picker_hide_icon: Hide Input Icon
  - date_picker_default_date: Default Date
  - date_picker_allow_input: Allow Input
  - date_picker_input: Input Field
  - date_picker_label: Label
  - date_picker_on_change: onChange
  - date_picker_on_close: onClose
  # - date_picker_range: Range
  - date_picker_quick_pick_react: Range (Quick Pick)
  - date_picker_quick_pick_range_limit: Range (Quick Pick w/ “This” Range limit)
  - date_picker_quick_pick_custom: Custom Quick Pick Dates
  - date_picker_quick_pick_custom_override: Custom Quick Pick Dates (append to defaults)
  - date_picker_quick_pick_default_date: Range (Quick Pick w/ Default Date)
  # - date_picker_range_pattern: Range with 2 Date Pickers and a Quick Pick
  - date_picker_and_dropdown_range: Range with Dropdown and 2 Date Pickers
  - date_picker_format: Format
  - date_picker_disabled: Disabled Dates
  - date_picker_min_max: Min Max
  - date_picker_error: Error
  - date_picker_flatpickr_methods: Flatpickr Methods
  - date_picker_hooks: Hooks
  - date_picker_year_range: Year Range
  - date_picker_margin_bottom: Margin Bottom
  - date_picker_inline: Inline
  - date_picker_month_and_year: Month & Year Only
  - date_picker_week: Week
  - date_picker_time: Time Selection
  - date_picker_positions: Custom Positions
  - date_picker_positions_element: Custom Position (based on element)
