appConfig:
    secretKeyBase: ENC[AES256_GCM,data:cbjB4yML/kL3c/rAblhzaVeKa1zhSN7rBnTyxPf2XGW/RP12RY8ix1aKqjvYuWbYe4dlJKSa+7tF+eAjx2uoH4TNzbExH05xXdbuxlnymUSObGrYGJ70lYKUMlfWJNTOBpAGRff6F4MOQfCmDc9mL2AwLHtyAW8Ag3ZVczTTF5Q=,iv:QescmNxHPF5E2d0RTDe7RcsWd7bKUQHVQlIqIBr/CdE=,tag:rTJHGL3rp/F2CoGa8ZVDQw==,type:str]
font_awesome_auth_token: ENC[AES256_GCM,data:/EnZ9xeMiC8kWu+V93mQsRN7VwAxDJ5zCLR2mX11hogJNgw4,iv:dWEi6jeIdkGLPVbVwhTKVRCLelJ96S6T56RX3m/Hmrc=,tag:pZUEN2eUhk99OIYf/YCELg==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:205083374951:key/405f40cd-a18a-40ed-bf2f-a0e7816a9a5c
        created_at: '2021-05-04T13:29:39Z'
        enc: AQICAHgujLkoWj/2YBLvu57MUrNOqZOY5uV5l5pH7MV/vzKMBgHTnmDEbzjKBtaGjo87ZHWTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIaqYdGEL0EF2r2PZAgEQgDvwWWsS5A7FWfwB3rrTmt6J6UdZTmUkrhRLnH6srV6DEbHp2yqDraQ28a6fdaWNMTB7fMAB0LQAbkajAw==
        aws_profile: ""
    -   arn: arn:aws:kms:us-east-1:205083374951:key/405f40cd-a18a-40ed-bf2f-a0e7816a9a5c
        role: arn:aws:iam::205083374951:role/UX
        created_at: '2021-05-04T13:29:39Z'
        enc: AQICAHgujLkoWj/2YBLvu57MUrNOqZOY5uV5l5pH7MV/vzKMBgEE3OFeziYP6WS3NxqIWDM/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhRUhuLS0NCo1dXEUAgEQgDuDkNdp2Z+bsgPWMoxeihmQFsEvkmsgLZO5jb3kpvMzklu9+3f2xuprFFPh3+Ul87PywFo/grB7rcaqmw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-11-16T19:58:27Z'
    mac: ENC[AES256_GCM,data:RZJ5vvBj4fmvLw+2B+b3r9y7oHUsKmGqx2V0NXXFggQ9hXTs8b8/ZMo4JCrkUDr5sLR2vvBsABWRtje+5Dxd9MmUaMhCUxDmwcJmsbUPARiuzMg9Ugrhs7/k2xYl9MvxIRGdB/tnX4PZFInqSOpgGx4/dHrNys0okwFEZKwjH4A=,iv:6lh1LTm/ob6QIkMWvw9pQtGaMUEQI5QBdhgyeg4udro=,tag:ZPpupxCyvlPD8OIEbm/HoA==,type:str]
    pgp:
    -   created_at: '2021-05-04T13:29:39Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2NdqJ8wZEUFARAAlyV0PYWoGcCxuO7LmtMMfpK2OZ6AoZscPloeZY30abjT
            McRcu9FzZpAvLqxAJnu7alZBe3g70cR26Rb7IsmyTgbYoHi2RYBnoZ8TZ3IYB2WU
            OE20udtbZ3QTeyKC+1Oit/hu+tKbY4WVAh+74H8TiqPhWizVzZ+NBsYsw75veXgG
            d6MjS4PPqBWYbhCSEuJdNCbfJXFbFAhmFzTMiFnX9Dip0SKVdjAnf2ghclKyAxha
            oY3p0ODkwIGfcOVGee5XkIQ/CMGVaCdSs68bSN2fFn/R4x84knNiJcb6ZoUAWWtC
            98KSCvPgKf6Jo/NdK0d3t3kirkdIaxQfiR+GL5hNRcZppu3x9S/6i0FbmLfUjPyL
            M9qB22Gtcv1BNNPssgUvGt1a1aXMuZYDoc6qnYhJyAyW0+IIsMI0J4DhfsEvx0XN
            yWAKApQBKgrBNjlDqZKgmc5mkXjUA55CVaJfTmBQBqUffSi+PQm3+tzpo6oylSea
            jY4GlAYn54qGq+zAkIPr1D7tJgwuVM123rmjW5Jpkub03y0g78dhxeZR7vlbKo4k
            ld3zfKGhCBtuwiYiNitC2nOQDSu6IrBfdRfC5dbLux81MN49EWJhPiez2ayr2KMv
            RpjZSpnlnrVBpyHWiYwy/GKCvGJiLnztz1dFRBtf6MFanyGeLUxF50r1QKlPrYvS
            5gGS62ISaGmKGTqj+h6ltPtxITP7RYajxSR1D6gUYXSJYYDgrAfjIz0tYP8L7eh7
            4eQzjHEOZkfYreN//7eIMAbkevm2gOiUTG4vJ6ipg7/ZeuJ5u5VnAA==
            =AiQN
            -----END PGP MESSAGE-----
        fp: C534CBAA229396B3FFC0CBB8FEFCDD8B6EB6B73B
    -   created_at: '2021-05-04T13:29:39Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA4Ms0+/IoZU/AQgAd0TtlrD5KESKe+ga2XlwBT0ArfGLSy+Gm6FCB1Xm+1c2
            e6gdmS2uNlh8vw3FhqvdpZ9SoXa9Mq8ffDQKARtfiqdKxsevPKuKtTmJxHeMBO1h
            girtJP6BLLNMU6od9SzOTR/ciSoJ0UX0hu+EwDFsx/qGoGgZ33rd23vlmpRp+t4x
            McboZefeo9jtr6U7C++ICTWt/Easqhcyg16+A4idsvziNUoK32GouJWJrVm3OmTG
            IuHkb/WMmc6KUEyBnnqkMYqp4e5881vKW9rfwNDPbKSGJ6ISycw1FRPVVSH/idWh
            99ccUZe9ng0HJVxDh1Kedpq2PSEsazteZZ++AOcW6dLmAVWEHugoFzDogauSGqN8
            m2cAKWKoDeWnRLrVli3ycmOm0ERNzvlRXL+E3/PI9ikF8NT1efIXhllKVykaUBgi
            5uSl8tw5mVoSyrvqpJfwS9nn4oY+6HsA
            =49cY
            -----END PGP MESSAGE-----
        fp: 181D7230C1982F01D9751710F0C07D7B2AC4F268
    unencrypted_suffix: _unencrypted
    version: 3.5.0
