examples:
  rails:
  - progress_step_default: Default
  - progress_step_vertical: Vertical
  - progress_step_tracker: Tracker
  - progress_step_color: Color
  - progress_step_custom_icon: Custom Icon
  - progress_step_tooltip: Tooltip

  react:
  - progress_step_default: Default
  - progress_step_vertical: Vertical
  - progress_step_tracker: Tracker
  - progress_step_color: Color
  - progress_step_custom_icon: Custom Icon
  - progress_step_tracker_click_events: Using State
