examples:

  rails:
  - toggle_default: Sizes
  - toggle_checked: Default State
  - toggle_name: Name and Value
  - toggle_custom: Custom checkbox input
  - toggle_custom_radio: Custom radio inputs

  react:
  - toggle_default: Default
  - toggle_accessibility: Toggle Accessibility
  - toggle_data: Toggle Data Props
  - toggle_custom_radio: Custom radio inputs

