examples:
  rails:
  - default_nav: Default
  - with_icons_nav: With Icons
  - with_img_nav: With Custom Icon
  - no_highlight_nav: No Highlight
  - borderless_nav: No Borders
  - subtle_nav: Subtle Variant
  - subtle_with_icons_nav: Subtle With Icons
  - collapsible_nav: Collapsible Nav
  - collapsible_nav_emphasize: Collapsible Nav with Emphasize Styling
  - subtle_no_highlight_nav: Subtle No Highlight
  - bold_vertical_nav: Bold Variant
  - horizontal_nav: Horizontal Nav
  - subtle_horizontal_nav: Subtle Horizontal Nav
  - bold_horizontal_nav: Bold Horizontal Nav
  - block_nav: Block
  - block_no_title_nav: Without Title
  - new_tab: Open in a New Tab

  react:
  # - default_nav: Default
  # - with_icons_nav: With Icons
  # - with_img_nav: With Custom Icon
  # - no_highlight_nav: No Highlight
  # - borderless_nav: No Borders
  # - subtle_nav: Subtle Variant
  # - subtle_with_icons_nav: Subtle With Icons
  - collapsible_nav: Collapsible Nav
  - collapsible_nav_emphasize: Collapsible Nav with Emphasize Styling
  - collapsible_nav_custom: Collapsible Nav With Custom Toggling
  - subtle_no_highlight_nav: Subtle No Highlight
  - bold_vertical_nav: Bold Variant
  - horizontal_nav: Horizontal Nav
  # - subtle_horizontal_nav: Subtle Horizontal Nav
  # - bold_horizontal_nav: Bold Horizontal Nav
  # - block_nav: Block
  # - block_no_title_nav: Without Title
  # - new_tab: Open in a New Tab
