examples:

  rails:
  - home_address_street_default: Default
  - home_address_street_emphasis: Emphasis
  - home_address_street_modified: Modified
  - home_address_street_link: Link

  react:
  - home_address_street_default: Default
  - home_address_street_emphasis: Emphasis
  - home_address_street_modified: Modified
  - home_address_street_link: Link
  - home_address_street_formatting: Formatting

  swift:
  - home_address_street_default_swift: Default
  - home_address_street_emphasis_swift: Emphasis
  - home_address_street_modified_swift: Modified
  - home_address_street_link_swift: Link
  - home_address_street_props_swift: ""
