examples:

  rails:
  - radio_default: Default
  - radio_custom: Custom
  - radio_error: With Error
  - radio_options: With Options
  - radio_alignment: Alignment
  - radio_disabled: Disabled
  - radio_custom_children: Custom Children

  react:
  - radio_default: Default
  - radio_custom: Custom
  - radio_error: With Error
  - radio_alignment: Alignment
  - radio_disabled: Disabled
  - radio_custom_children: Custom Children

  swift:
  - radio_default_swift: Default
  - radio_custom_swift: Custom
  - radio_error_swift: With Error
  - radio_orientation_swift: Orientation
  - radio_alignment_swift: Alignment
  - radio_spacing_swift: Spacing
  - radio_padding_swift: Padding
  - radio_subtitle_swift: Subtitle
  - radio_props_swift: ""