examples:

  rails:
  - time_default: Sizes
  - time_timestamp: Timestamp Values

  react:
  - time_default: Sizes
  - time_timestamp: Timestamp Values
  - time_timezone: Handling Timezones
  - time_align: Alignment
