examples:

  rails:
  - passphrase_default: Default
  - passphrase_confirmation: Confirmation
  - passphrase_meter_settings: Meter Settings
  - passphrase_input_props: Input Props
  - passphrase_tips: Tips
  - passphrase_strength_change: Strength Change
  - passphrase_common: Common Passphrases
  - passphrase_breached: Breached Passphrases

  react:
  - passphrase_default: Default
  - passphrase_confirmation: Confirmation
  - passphrase_meter_settings: Meter Settings
  - passphrase_input_props: Input Props
  - passphrase_tips: Tips
  - passphrase_strength_change: Strength Change
  - passphrase_common: Common Passphrases
  - passphrase_breached: Breached Passphrases
  - passphrase_required_indicator: Required Indicator
