examples:
  rails:
    - checkbox_default: Default
    - checkbox_checked: Load as checked
    - checkbox_custom: Custom Checkbox
    - checkbox_error: Default w/ Error
    - checkbox_options: Checkbox w/ Options
    - checkbox_indeterminate: Indeterminate Checkbox
    - checkbox_disabled: Disabled Checkbox
    - checkbox_form: Form and Hidden Input
    - checkbox_required_indicator: Required Indicator

  react:
  - checkbox_default: Default
  - checkbox_checked: Load as checked
  - checkbox_react_hook: React Hook Form
  - checkbox_custom: Custom Checkbox
  - checkbox_error: Default w/ Error
  - checkbox_indeterminate: Indeterminate Checkbox
  - checkbox_disabled: Disabled Checkbox
  - checkbox_required_indicator: Required Indicator

  swift:
    - checkbox_default_swift: Default
    - checkbox_error_swift: Default w/ Error
    - checkbox_indeterminate_swift: Indeterminate Checkbox
    - checkbox_props_swift: ""
    
