examples:
  rails:
  - default_nav: Default
  - with_icons_nav: With Icons
  - no_highlight_nav: No Highlight
  - subtle_nav: Subtle Variant
  - subtle_with_icons_nav: Subtle With Icons
  - subtle_no_highlight_nav: Subtle No Highlight
  - horizontal_nav: Horizontal Nav
  - block_nav: Block
  - block_no_title_nav: Without Title
  react:
  - default_nav: Default
  - horizontal_nav: Horizontal Nav
  - block_nav: Block Nav
  - block_no_title_nav: Without Title
