examples:
  rails:
  - button_default: Button Variants
  - button_reaction: Reaction Button
  - button_full_width: Button Full Width
  - button_link: Button Links
  - button_loading: Button Loading
  - button_block_content: Button Block Content
  - button_icon_options: Button Icon Options
  - button_accessibility: Button Accessibility Options
  - button_options: Button Additional Options
  - button_size: Button Size
  - button_form: Button Form Attribute
  - button_managed_disabled: Button Toggle Disabled State
  - button_managed_disabled_helper: Button Toggle Disabled State Helper
  - button_icon_variant: Icon Button Variant
  
  react:
  - button_default: Button Variants
  - button_reaction: Reaction Button
  - button_full_width: Button Full Width
  - button_link: Button Links
  - button_loading: Button Loading
  - button_block_content: Button Block Content
  - button_icon_options: Button Icon Options
  - button_accessibility: Button Accessibility Options
  - button_options: Button Additional Options (onClick)
  - button_size: Button Size
  - button_form: Button Form Attribute
  - button_hover: Button Hover
  - button_icon_variant: Icon Button Variant

  swift:
  - button_default_swift: Button Variants
  - button_full_width_swift: Button Full Width
  - button_icon_options_swift: Button Icon Options
  - button_circle_swift: Circle Button
  - button_size_swift: Button Size
  - button_reaction_swift: Button Reaction
  - button_props_swift: ""
