examples:
  rails:
  - button_default: Button Variants
  - button_full_width: Button Full Width
  - button_link: Button Links
  - button_loading: Button Loading
  - button_block_content: Button Block Content
  - button_with_icons: Button With Icons
  - button_accessibility: Button Accessibility Options
  - button_options: Button Additional Options
  - button_size: Button Size
  - button_form: Button Form Attribute
  react:
  - button_default: Button Variants
  - button_full_width: Button Full Width
  - button_link: Button Links
  - button_loading: Button Loading
  - button_block_content: Button Block Content
  - button_with_icons: Button With Icons
  - button_accessibility: Button Accessibility Options
  - button_options: Button Additional Options (onClick)
  - button_size: Button Size
  - button_form: Button Form Attribute
