examples:
  rails:
    - star_rating_default: Default
    - star_rating_color_options: Color Options
    - star_rating_background_options: Background Options
    - star_rating_hide: Layout Options
    - star_rating_number_config: Number Config
    - star_rating_size_options: Size Options
    - star_rating_interactive: Interactive

  react:
    - star_rating_default: Default
    - star_rating_color_options: Color Options
    - star_rating_background_options: Background Options
    - star_rating_hide: Layout Options
    - star_rating_number_config: Number Config
    - star_rating_size_options: Size Options
    