examples:
  rails:
  - copy_button_default: Default
  - copy_button_from: Copy From
  - copy_button_hook_rails: Copy Hook
  
  react:
  - copy_button_default: Default
  - copy_button_from: Copy From
  - copy_button_hook: Copy Hook
  - copy_button_icon_variant: Icon Variant
