examples:
  
  rails:
  - progress_step_default: Default
  - progress_step_child: Child
  - progress_step_vertical: Vertical
  - progress_step_dark: Dark
  
  
  react:
  - progress_step_default: Default
  - progress_step_child: Child
  - progress_step_vertical: Vertical
  - progress_step_dark: Dark
